import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28p;
          }
        `}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="text, blog, translator, convertor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

      <main className={styles.main}>
        <h1 className={styles.title}>Sakar's Blog</h1>
        <Image
          className={styles.myImg}
          src="/home.jpg"
          width={237}
          height={158}
        />

        <p className={styles.description}>Simple and Clean Blog</p>
        <div className={styles.blogs}>
        <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
